name: Pull Request
description: Template for pull requests
title: ""
body:
  - type: markdown
    attributes:
      value: Thanks for contributing to this project!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your changes here
      placeholder: A clear and concise description of your changes...
    validations:
      required: true
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Link related issues here (e.g., Closes #123)
      placeholder: Closes #
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have tested my changes
          required: true
        - label: I have updated documentation if needed
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/xivselch/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

