name: Feature Request
description: Suggest an idea for this project
title: "feat: "
labels: ["enhancement"]
type: feature
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a feature!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like
      placeholder: A clear and concise description of the feature...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: Describe the problem this feature would address...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/xivselch/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

